/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// ClusterQueuePreemptionApplyConfiguration represents a declarative configuration of the ClusterQueuePreemption type for use
// with apply.
//
// ClusterQueuePreemption contains policies to preempt Workloads from this
// ClusterQueue or the ClusterQueue's cohort.
//
// Preemption may be configured to work in the following scenarios:
//
// - When a Workload fits within the nominal quota of the ClusterQueue, but
// the quota is currently borrowed by other ClusterQueues in the cohort.
// We preempt workloads in other ClusterQueues to allow this ClusterQueue to
// reclaim its nominal quota. Configured using reclaimWithinCohort.
// - When a Workload doesn't fit within the nominal quota of the ClusterQueue
// and there are admitted Workloads in the ClusterQueue with lower priority.
// Configured using withinClusterQueue.
// - When a Workload may fit while both borrowing and preempting
// low priority workloads in the Cohort. Configured using borrowWithinCohort.
// - When FairSharing is enabled, to maintain fair distribution of
// unused resources. See FairSharing documentation.
//
// The preemption algorithm tries to find a minimal set of Workloads to
// preempt to accomomdate the pending Workload, preempting Workloads with
// lower priority first.
type ClusterQueuePreemptionApplyConfiguration struct {
	// reclaimWithinCohort determines whether a pending Workload can preempt
	// Workloads from other ClusterQueues in the cohort that are using more than
	// their nominal quota. The possible values are:
	//
	// - `Never` (default): do not preempt Workloads in the cohort.
	// - `LowerPriority`: **Classic Preemption** if the pending Workload
	// fits within the nominal quota of its ClusterQueue, only preempt
	// Workloads in the cohort that have lower priority than the pending
	// Workload. **Fair Sharing** only preempt Workloads in the cohort that
	// have lower priority than the pending Workload and that satisfy the
	// Fair Sharing preemptionStategies.
	// - `Any`: **Classic Preemption** if the pending Workload fits within
	// the nominal quota of its ClusterQueue, preempt any Workload in the
	// cohort, irrespective of priority. **Fair Sharing** preempt Workloads
	// in the cohort that satisfy the Fair Sharing preemptionStrategies.
	ReclaimWithinCohort *kueuev1beta2.PreemptionPolicy `json:"reclaimWithinCohort,omitempty"`
	// borrowWithinCohort determines whether a pending Workload can preempt
	// Workloads from other ClusterQueues in the cohort if the workload requires borrowing.
	// May only be configured with Classical Preemption, and __not__ with Fair Sharing.
	BorrowWithinCohort *BorrowWithinCohortApplyConfiguration `json:"borrowWithinCohort,omitempty"`
	// withinClusterQueue determines whether a pending Workload that doesn't fit
	// within the nominal quota for its ClusterQueue, can preempt active Workloads in
	// the ClusterQueue. The possible values are:
	//
	// - `Never` (default): do not preempt Workloads in the ClusterQueue.
	// - `LowerPriority`: only preempt Workloads in the ClusterQueue that have
	// lower priority than the pending Workload.
	// - `LowerOrNewerEqualPriority`: only preempt Workloads in the ClusterQueue that
	// either have a lower priority than the pending workload or equal priority
	// and are newer than the pending workload.
	WithinClusterQueue *kueuev1beta2.PreemptionPolicy `json:"withinClusterQueue,omitempty"`
	// maxEvictionsPerSchedulingPass caps the number of bound Workloads that
	// the scheduler may relocate during a single scheduling pass to make room
	// for a pending Workload on an Ordered topology level (compaction).
	// Compaction is the operation of moving an already-admitted Workload to a
	// different contiguous range on a 1-D ordered fabric so that a fragmented
	// free area can be merged into a contiguous run that the pending Workload
	// can occupy. Examples of ordered fabrics include NVLink and Infinity
	// Fabric rings, Slingshot dragonfly inter-group links, and any topology
	// where rank-to-position adjacency drives collective bandwidth.
	//
	// Possible values:
	// - nil or 0 (default): never compact. The scheduler only places
	// pending Workloads on existing contiguous free runs.
	// - N > 0: compact up to N Workloads per pass. Higher values admit
	// more pending Workloads at the cost of disrupting more running
	// Workloads. There is no special "infinity" value; setting N to a
	// value at or above the chain capacity is effectively unbounded.
	//
	// Compaction is orthogonal to classical priority-based preemption: it
	// only relocates same-or-lower-priority bound Workloads, never
	// displacing a higher-priority Workload to admit a lower-priority one.
	// Among feasible compaction plans, the scheduler picks the one with the
	// fewest evictions, then the lowest-impact victim set per
	// CandidatesOrdering.
	//
	// This field has effect only when the assigned ResourceFlavor's Topology
	// declares a level with `ordered: true` and the PodSet's
	// `podset-slice-required-topology` resolves to that level. On
	// non-ordered topologies it is ignored.
	MaxEvictionsPerSchedulingPass *int32 `json:"maxEvictionsPerSchedulingPass,omitempty"`
}

// ClusterQueuePreemptionApplyConfiguration constructs a declarative configuration of the ClusterQueuePreemption type for use with
// apply.
func ClusterQueuePreemption() *ClusterQueuePreemptionApplyConfiguration {
	return &ClusterQueuePreemptionApplyConfiguration{}
}

// WithReclaimWithinCohort sets the ReclaimWithinCohort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReclaimWithinCohort field is set to the value of the last call.
func (b *ClusterQueuePreemptionApplyConfiguration) WithReclaimWithinCohort(value kueuev1beta2.PreemptionPolicy) *ClusterQueuePreemptionApplyConfiguration {
	b.ReclaimWithinCohort = &value
	return b
}

// WithBorrowWithinCohort sets the BorrowWithinCohort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BorrowWithinCohort field is set to the value of the last call.
func (b *ClusterQueuePreemptionApplyConfiguration) WithBorrowWithinCohort(value *BorrowWithinCohortApplyConfiguration) *ClusterQueuePreemptionApplyConfiguration {
	b.BorrowWithinCohort = value
	return b
}

// WithWithinClusterQueue sets the WithinClusterQueue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WithinClusterQueue field is set to the value of the last call.
func (b *ClusterQueuePreemptionApplyConfiguration) WithWithinClusterQueue(value kueuev1beta2.PreemptionPolicy) *ClusterQueuePreemptionApplyConfiguration {
	b.WithinClusterQueue = &value
	return b
}

// WithMaxEvictionsPerSchedulingPass sets the MaxEvictionsPerSchedulingPass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxEvictionsPerSchedulingPass field is set to the value of the last call.
func (b *ClusterQueuePreemptionApplyConfiguration) WithMaxEvictionsPerSchedulingPass(value int32) *ClusterQueuePreemptionApplyConfiguration {
	b.MaxEvictionsPerSchedulingPass = &value
	return b
}
